services:
  ldcgoapi:
    image: landscapedatacommons/ldc-go-api:1.0.8
    build:
      context: .
      args:
        BUILD_DATE: ${BUILD_DATE}
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy: 
        condition: on-failure
    ports:
      - "8080:8080" 
    volumes:
      - ./config.yaml:/app/config.yaml:ro  # Bind
    networks:
      - ldc-go-net
networks:
  ldc-go-net:
    external: true