package schemas

// dataHorizontalFluxSchema defines the column names and types for the `dataHorizontalFlux` table.
var DataHorizontalFluxSchema = map[string]string{
    "rid": "integer",
    "ProjectKey": "text",
    "PrimaryKey": "text",
    "BoxID": "text",
    "StackID": "text",
    "Height": "double precision",
    "DateEstablished": "date",
    "Description": "text",
    "openingSize": "text",
    "processMethod": "text",
    "ovenTemp": "integer",
    "BoxType": "integer",
    "azimuth": "text",
    "SamplerType": "text",
    "InletArea": "double precision",
    "Location": "text",
    "ItemType": "text",
    "trapOpeningArea": "double precision",
    "GPSCoordSys": "text",
    "Datum": "text",
    "Zone": "text",
    "Easting": "double precision",
    "Northing": "double precision",
    "Longitude": "double precision",
    "Latitude": "double precision",
    "RecKey": "text",
    "collectDate": "date",
    "beakerNbr": "text",
    "emptyWeight": "double precision",
    "recordedWeight": "double precision",
    "sedimentWeight": "double precision",
    "daysExposed": "integer",
    "sedimentGperDay": "double precision",
    "sedimentArchived": "integer",
    "Notes": "text",
    "sedimentGperDayByInlet": "double precision",
    "SeqNo": "integer",
    "SampleCompromised": "integer",
    "DBKey": "text",
    "DateLoadedInDb": "date",
    "DateVisited": "date",
}
