package schemas

// dataGapSchema defines the column names and types for the `dataGap` table.
var DataGapSchema = map[string]string{
    "rid": "integer",
    "PrimaryKey": "text",
    "DBKey": "text",
    "ProjectKey": "text",
    "RecType": "text",
    "SeqNo": "integer",
    "GapStart": "double precision",
    "GapEnd": "double precision",
    "Gap": "double precision",
    "LineKey": "text",
    "RecKey": "text",
    "FormDate": "date",
    "DateModified": "date",
    "FormType": "text",
    "Direction": "text",
    "Measure": "integer",
    "LineLengthAmount": "double precision",
    "GapMin": "double precision",
    "GapData": "integer",
    "PerennialsCanopy": "boolean",
    "AnnualGrassesCanopy": "boolean",
    "AnnualForbsCanopy": "boolean",
    "OtherCanopy": "boolean",
    "Notes": "text",
    "NoCanopyGaps": "integer",
    "NoBasalGaps": "integer",
    "DateLoadedInDb": "date",
    "PerennialsBasal": "boolean",
    "AnnualGrassesBasal": "boolean",
    "AnnualForbsBasal": "boolean",
    "OtherBasal": "boolean",
    "source": "text",
    "DateVisited": "date",
}
