package schemas

// dataSpeciesInventorySchema defines the column names and types for the `dataSpeciesInventory` table.
var DataSpeciesInventorySchema = map[string]string{
    "rid": "integer",
    "PrimaryKey": "text",
    "DBKey": "text",
    "ProjectKey": "text",
    "Species": "text",
    "DENSITY": "integer",
    "LineKey": "text",
    "RecKey": "text",
    "FormType": "text",
    "FormDate": "date",
    "SpecRichMethod": "integer",
    "SpecRichMeasure": "integer",
    "SpecRichNbrSubPlots": "integer",
    "SpecRich1Container": "integer",
    "SpecRich1Shape": "integer",
    "SpecRich1Dim1": "double precision",
    "SpecRich1Dim2": "double precision",
    "SpecRich1Area": "double precision",
    "SpecRich2Container": "integer",
    "SpecRich2Shape": "integer",
    "SpecRich2Dim1": "double precision",
    "SpecRich2Dim2": "double precision",
    "SpecRich2Area": "double precision",
    "SpecRich3Container": "integer",
    "SpecRich3Shape": "integer",
    "SpecRich3Dim1": "double precision",
    "SpecRich3Dim2": "double precision",
    "SpecRich3Area": "double precision",
    "SpecRich4Container": "integer",
    "SpecRich4Shape": "integer",
    "SpecRich4Dim1": "double precision",
    "SpecRich4Dim2": "double precision",
    "SpecRich4Area": "double precision",
    "SpecRich5Container": "integer",
    "SpecRich5Shape": "integer",
    "SpecRich5Dim1": "double precision",
    "SpecRich5Dim2": "double precision",
    "SpecRich5Area": "double precision",
    "SpecRich6Container": "integer",
    "SpecRich6Shape": "integer",
    "SpecRich6Dim1": "double precision",
    "SpecRich6Dim2": "double precision",
    "SpecRich6Area": "double precision",
    "Notes": "text",
    "source": "text",
    "DateLoadedInDb": "date",
    "DateVisited": "date",
}
