package schemas

// dataSoilHorizonsSchema defines the column names and types for the `dataSoilHorizons` table.
var DataSoilHorizonsSchema = map[string]string{
    "rid": "integer",
    "ProjectKey": "text",
    "PrimaryKey": "text",
    "DBKey": "text",
    "HorizonKey": "text",
    "HorizonDepthUpper": "double precision",
    "HorizonDepthLower": "double precision",
    "DepthUOM": "text",
    "HorizonName": "text",
    "Texture": "text",
    "TextureModifier": "text",
    "pH": "double precision",
    "EC": "double precision",
    "Effervescence": "text",
    "ClayPct": "double precision",
    "SandPct": "double precision",
    "StructureGrade": "text",
    "StructureSize": "text",
    "StructureType": "text",
    "StructureQuality": "text",
    "Hue": "text",
    "Value": "integer",
    "Chroma": "integer",
    "ColorMoistDry": "text",
    "HorizonNotes": "text",
    "SiltPct": "double precision",
    "FragVolGravel": "double precision",
    "FragVolCobble": "double precision",
    "FragVolStone": "double precision",
    "FragVolNodule": "double precision",
    "FragVolDurinode": "double precision",
    "HorizonNumber": "integer",
    "source": "text",
    "DateVisited": "date",
    "DateLoadedInDb": "date",
}
