package schemas

// tblRHEMSchema defines the column names and types for the `tblRHEM` table.
var TblRHEMSchema = map[string]string{
    "rid": "integer",
    "ProjectKey": "text",
    "PrimaryKey": "text",
    "DateVisited": "date",
    "Precipitation_Long_Term_MEAN": "double precision",
    "Runoff_Long_Term_MEAN": "double precision",
    "Sediment_Yield_Long_Term_MEAN": "double precision",
    "Soil_Loss_Long_Term_MEAN": "double precision",
    "Precipitation_Yearly_Maximum_Daily_2_YR": "double precision",
    "Precipitation_Yearly_Maximum_Daily_5_YR": "double precision",
    "Precipitation_Yearly_Maximum_Daily_10_YR": "double precision",
    "Precipitation_Yearly_Maximum_Daily_25_YR": "double precision",
    "Precipitation_Yearly_Maximum_Daily_50_YR": "double precision",
    "Precipitation_Yearly_Maximum_Daily_100_YR": "double precision",
    "Precipitation_Yearly_Totals_2_YR": "double precision",
    "Precipitation_Yearly_Totals_5_YR": "double precision",
    "Precipitation_Yearly_Totals_10_YR": "double precision",
    "Precipitation_Yearly_Totals_25_YR": "double precision",
    "Precipitation_Yearly_Totals_50_YR": "double precision",
    "Precipitation_Yearly_Totals_100_YR": "double precision",
    "Runoff_Annual_Maximum_Daily_2_YR": "double precision",
    "Runoff_Annual_Maximum_Daily_5_YR": "double precision",
    "Runoff_Annual_Maximum_Daily_10_YR": "double precision",
    "Runoff_Annual_Maximum_Daily_25_YR": "double precision",
    "Runoff_Annual_Maximum_Daily_50_YR": "double precision",
    "Runoff_Annual_Maximum_Daily_100_YR": "double precision",
    "Runoff_Annual_Totals_2_YR": "double precision",
    "Runoff_Annual_Totals_5_YR": "double precision",
    "Runoff_Annual_Totals_10_YR": "double precision",
    "Runoff_Annual_Totals_25_YR": "double precision",
    "Runoff_Annual_Totals_50_YR": "double precision",
    "Runoff_Annual_Totals_100_YR": "double precision",
    "Soil_Loss_Yearly_Maximum_Daily_2_YR": "double precision",
    "Soil_Loss_Yearly_Maximum_Daily_5_YR": "double precision",
    "Soil_Loss_Yearly_Maximum_Daily_10_YR": "double precision",
    "Soil_Loss_Yearly_Maximum_Daily_25_YR": "double precision",
    "Soil_Loss_Yearly_Maximum_Daily_50_YR": "double precision",
    "Soil_Loss_Yearly_Maximum_Daily_100_YR": "double precision",
    "Soil_Loss_Yearly_Totals_2_YR": "double precision",
    "Soil_Loss_Yearly_Totals_5_YR": "double precision",
    "Soil_Loss_Yearly_Totals_10_YR": "double precision",
    "Soil_Loss_Yearly_Totals_25_YR": "double precision",
    "Soil_Loss_Yearly_Totals_50_YR": "double precision",
    "Soil_Loss_Yearly_Totals_100_YR": "double precision",
    "Sediment_Yield_Yearly_Maximum_Daily_2_YR": "double precision",
    "Sediment_Yield_Yearly_Maximum_Daily_5_YR": "double precision",
    "Sediment_Yield_Yearly_Maximum_Daily_10_YR": "double precision",
    "Sediment_Yield_Yearly_Maximum_Daily_25_YR": "double precision",
    "Sediment_Yield_Yearly_Maximum_Daily_50_YR": "double precision",
    "Sediment_Yield_Yearly_Maximum_Daily_100_YR": "double precision",
    "Sediment_Yield_Yearly_Totals_2_YR": "double precision",
    "Sediment_Yield_Yearly_Totals_5_YR": "double precision",
    "Sediment_Yield_Yearly_Totals_10_YR": "double precision",
    "Sediment_Yield_Yearly_Totals_25_YR": "double precision",
    "Sediment_Yield_Yearly_Totals_50_YR": "double precision",
    "Sediment_Yield_Yearly_Totals_100_YR": "double precision",
    "DateLoadedInDb": "date",
}
